config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  root "welcome#index"
  get 'welcome/index'
  resources :coins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :mining_type
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
    has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    def set_locale 
    
      if params[:locale] 

        cookies[:locale] = params[:locale]
        
      end
      
      if cookies[:locales]
        if cookies[:locale] != I18n.locale
            I18n.locale = cookies[:locale]
          end
      end
      
    end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: %i[new create edit update]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :image, :mining_type_id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronyn)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    cookies[:user_name] = "João Gabriel"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def data_br(data_us)
        data_us.strftime("%d/%m/%Y")
    end
    
    def ambiente_rails
        if Rails.env.development?
            "Desenvolvimento"
        elsif Rails.env.production?
            "Produção"
        else 
            "Teste"
        end
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
<h1> <%= t('activerecord.models.coin: ') + @coin.description%> </h1>
  <form>
  
  <div class = "form-group">
      <%= label_tag nil, @coin.class.human_attribute_name(:description) %>
      <%= text_field_tag nil, coin.description, class: "form-control", disabled: true %>       
  </div>
  <div class = "form-group">
      <%= label_tag nil, @coin.class.human_attribute_name(:acronym) %>
      <%= text_field_tag nil, coin.acronym, class: "form-control", disabled: true %>       
  </div>
  <div class = "form-group">
      <%= label_tag nil, @coin.class.human_attribute_name(:image) %>
      <%= text_field_tag nil, coin.image, class: "form-control", disabled: true %>       
  </div>
  <div class = "form-group">
      <%= label_tag nil, @coin.class.human_attribute_name(:mining_type) %>
      <%= text_field_tag nil, coin.mining_type.description, class: "form-control", disabled: true %>       
  </div>
  
  </form>
</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: "form-control", placeholder: "bitcoin" %>
  </div>

  <div class = "form-group">
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym, class: "form-control", placeholder: "BTC" %>
  </div>

  <div class = "form-group">
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image, class: "form-control", placeholder: "www.img.ur/bitcoin,png" %>
  </div>

  <div class = "form-group">
    <%= form.label :mining_type, style: "display: block" %>
     <%= form.select("mining_type_id", @mining_type_options, {include_blank: "selecione"}, class: "form-control") %> 
  </div>

  <div>
    <%= form.submit nil, class: "btn btn-primary mt-3" %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Show this coin", @coin, class: "btn btn-info" %> |
  <%= link_to "Back to coins", coins_path, class: "btn btn-info" %>
</div>

app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Coins</h1>

<div id="coins">
<table class = "table table-dark table-striped">
<thead>
<tr class = "">
    <td><%= t("activerecord.attributes.coin.description") %></td>
    <td><%= t("activerecord.attributes.coin.acronym") %></td>
    <td><%= t("activerecord.attributes.coin.image") %></td>
    <td><%= %></td>
  </tr>
</thead>
  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= coin.image %></td>
        <td><%= link_to t("links.show"), coin %></td>
        <td><%= link_to t("links.edit"), edit_coin_path(coin) %></td>
        <td><%= link_to t("links.destroy"), coin, method: :delete, data: {confirm: "tem certeza que deseja apagar?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= link_to t("links.new"), new_coin_path, class: "btn btn-primary" %>

app/views/coins/new.html.erb
<h1>New coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Back to coins", coins_path, class: "btn btn-info" %>
</div>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coin %>

<div>
  <%= link_to t('links.edit'), edit_coin_path(@coin), class: "btn btn-info my-3" %> |
  <%= link_to  "voltar", coins_path, class: "btn btn-info my-3" %>

  <%= button_to t("links.destroy"), @coin, method: :delete, class: "btn btn-danger" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class = "bg-dark text-white">
    <div class= "container-fluid">
      <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <%= link_to "Crypto Wallet", root_path(locale: 'pt-BR'), class: "navbar-brand text-white" %>
          <button class="navbar-toggler" type="button" >
            <span class="navbar-toggler-icon"></span> 
          </button>
          <div class="collapse navbar-collapse justify-content-end" >
            <div class="navbar-nav text-white">
              <%=link_to "Portuguese", root_path(locale:"pt-BR"), class: "nav-link text-white"%>
               <%=link_to "English", root_path(locale:"English"), class: "nav-link text-white"%>
            </div>
          </div>
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "form-group">
    <%= form.label t("activerecord.attributes.mining_type.description") , style: "display: block" %>
    <%= form.text_field :description, class: "form-control", placeholder: "Proof of Work" %>
  </div>

  <div class = "form-group">
    <%= form.label t("activerecord.attributes.mining_type.acronym"), style: "display: block" %>
    <%= form.text_field :acronyn, class: "form-control", placeholder: "POW" %>
  </div>

  <div >
    <%= form.submit nil, class: "btn btn-primary mt-3" %>
  </div>
<% end %>

app/views/mining_types/_mining_type.html.erb
<div id="<%= dom_id mining_type %>">
  <h1> <%= t('activerecord.models.mining_type: ') + @mining_type.description%> </h1>
  <form>
  
  <div class = "form-group">
      <%= label_tag nil, @mining_type.class.human_attribute_name(:description) %>
      <%= text_field_tag nil, mining_type.description, class: "form-control", disabled: true %>       
  </div>
  <div class = "form-group">
      <%= label_tag nil, @mining_type.class.human_attribute_name(:acronyn) %>
      <%= text_field_tag nil, mining_type.acronyn, class: "form-control", disabled: true %>       
  </div>
  
  
  </form>
</div>

app/views/mining_types/edit.html.erb
<h1>Editing mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to "Show this mining type", @mining_type, class: "btn btn-info" %> |
  <%= link_to "Back to mining types", mining_types_path, class: "btn btn-info" %>
</div>

app/views/mining_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t("new.mining_type") %></h1>

<div id="coins">
<table class = "table table-dark table-striped">
<thead>
<tr >
    <td><%= t("activerecord.attributes.mining_type.description") %></td>
    <td><%= t("activerecord.attributes.mining_type.acronym") %></td>
    
  </tr>
</thead>
  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronyn %></td>
        <td><%= link_to t("links.show"), mining_type %></td>
        <td><%= link_to t("links.edit"), edit_mining_type_path(mining_type) %></td>
        <td><%= link_to t("links.destroy"), mining_type, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= link_to t("links.new"), new_mining_type_path, class: "btn btn-primary" %>

app/views/mining_types/new.html.erb
<h1>New mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to "Back to mining types", mining_types_path, class: "btn btn-info" %>
</div>

app/views/mining_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mining_type %>

<div>
  <%= link_to "Edit this mining type", edit_mining_type_path(@mining_type), class: "btn btn-info my-3" %> |
  <%= link_to "Back to mining types", mining_types_path,  class: "btn btn-info my-3" %>

  <%= button_to "Destroy this mining type", @mining_type, method: :delete,  class: "btn btn-danger" %>
</div>

app/views/welcome/_footer.html.erb
<p class="font-weight-bold"> ooi </p>

app/views/welcome/index.html.erb
<div class=" bg-dark  text-light p-5 rounded-lg m-3">
  <h1 class="display-4">Crypto Wallet</h1>
  <p class="lead"><%= t("messages.welcome") %></p>
  <hr class="my-4">
  <p><%= t("messages.menu") %></p>
  <%= link_to "#{Coin.model_name.human}", coins_path, class: "btn btn-primary btn-lg " %>  
  <%= link_to "#{MiningType.model_name.human}", mining_types_path, class: "btn btn-primary btn-lg" %>  
  
  
</div>